version: '2'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=ipi
      - DB_PASSWORD=ipi
      - DB_NAME=jva324
    ports:
      - '15432:5432'
    volumes:
      # data - either a docker volume : (to be defined at the end)
      #- postgres-pgdata:/var/lib/postgresql/data
      # or a bind-mounted volume which is be easier to back up and use with OS tools :
      - ./volumes/pg-data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  #discovery-service:
  #  container_name: discovery-service
  #  build: ./discovery
  #  ports:
  #    - "8761:8761"
  commande-service:
    container_name: commande-service
    build: ./commande
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_JAVA_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/jva324
      - DB_USERNAME=ipi
      - DB_PASSWORD=ipi
    ports:
      - "8080:8080"
    depends_on:
      - db